[build]
  command = "npm ci --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10.8.2"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NEXT_PUBLIC_SUPABASE_URL = "https://yomnitxefrkuvnbnbhut.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvbW5pdHhlZnJrdXZuYm5iaHV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMzE3NDgsImV4cCI6MjA2NzYwNzc0OH0.Imw2JQVeQdAr-FjvBP_4Xbl2QxmREB8S_pfuFgr2GTQ"
  NEXT_PUBLIC_SITE_URL = "https://staging.booksweeps.com"
  NEXT_PUBLIC_READER_URL = "https://read.booksweeps.com"
  NEXT_PUBLIC_AUTHOR_URL = "https://app.booksweeps.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization" 